# Generated by Django 5.1.7 on 2025-04-02 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_app.book')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
