# Generated by Django 5.1.7 on 2025-04-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='description',
            field=models.CharField(default='add_description', max_length=255),
        ),
    ]
